root = "."
testdata_dir = "testdata"
tmp_dir = ".dev"

[build]
args_bin = ["-port", "8005"]
bin = "/app/.dev-air/templates"
cmd = "CGO_ENABLED=1 go build -tags dev -mod vendor -o ./.dev-air/templates main.go"
delay = 1000
exclude_dir = [
    "out",
    ".dev",
    "vendor",
    "testdata",
    ".git",
    "phishing-templates",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
#full_bin = "dlv exec --log-dest /.dev/dlv.log --accept-multiclient --headless --continue --listen 0.0.0.0:2345 --api-version 2 /app/.dev-air/templates --"
# to debug something early in the application like at boot up, then remove the continue flag
# this will make the debugger not start the program before a client attaches to it
#full_bin = "dlv exec --accept-multiclient --headless --continue --listen 0.0.0.0:2345 --api-version 2 /app/.dev-air/templates --"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = true                       #false
stop_on_error = true

[color]
#  app = "red"
#  build = "yellow"
#  main = "magenta"
#  runner = "green"
#  watcher = "cyan"

[log]
time = false
main_only = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
